---
# - name: Check if ANDROID_HOME exists
#   shell: 'echo $ANDROID_HOME'
#   register: android_check
#
# - name: "Execute"
#   debug:
#     msg: "ANDROID_HOME found !!!"
#   when: android_check.stdout.find('android') != -1
# TODO Finalizar
- set_fact:
    android_base_dir: /opt/android/android-sdk-linux
    android_from_source: true
    plaform_tool: platforms\;android-28
    build_tool: build-tools\;28.0.3

- name: "Ensure java enviroment is installed"
  include_tasks: java.yml

- name: "ANDROID: Install dependencies"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - zlib.i686
    - ncurses-libs.i686
    - bzip2-libs.i686

- name: "Copy installation file into tmp"
  copy:
    src: sdk-tools-linux-4333796.zip
    dest: "/tmp/sdk-tools-linux-4333796.zip"
    mode: 0664
  when: android_from_source == false

- name: "Download android sdk from source"
  get_url:
    url: 'https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip'
    dest: "/tmp/sdk-tools-linux-4333796.zip"
    mode: 0664
  when: android_from_source

- name: "Create installation directory"
  file:
    path: "{{android_base_dir}}"
    state: directory
    recurse: yes

- name: "Unarchive android sdk tools"
  unarchive:
    src: /tmp/sdk-tools-linux-4333796.zip
    dest: "{{ android_base_dir }}"
    owner: root
    group: root
    mode: 0775

- name: "Setup enviroment variable ANDROID_HOME"
  template:
    src: android_profile.sh.j2
    dest: /etc/profile.d/android.sh
    owner: root
    group: root
    mode: 0775

- name: "Clean installation file"
  file:
    path: "/tmp/sdk-tools-linux-4333796.zip"
    state: absent

- name: Create .android directory
  file:
    name: ~/.android
    state: directory
    mode: 0775

- name: Create repository config
  file:
    name: ~/.android/repositories.cfg
    state: touch
    mode: 0775

- name: "Update android sdk"
  shell: "{{android_base_dir}}/tools/bin/sdkmanager --update"

- name: "Accept Licenses"
  shell: "yes | {{android_base_dir}}/tools/bin/sdkmanager --licenses"

# TODO Fazer funcionar
- name: Add platform tools
  shell: "yes | {{android_base_dir}}/tools/bin/sdkmanager '{{ item }}'"
  with_items:
    - "{{plaform_tool}}"
    - "{{ build_tool }}"

# References
# ----> https://developer.android.com/studio/command-line/sdkmanager
