---
- set_fact:
    gradle_version: gradle-5.0
    gradle_base_dir: /opt/gradle
    gradle_from_source: true

- name: "Ensure java enviroment is installed"
  include_tasks: java.yml

- name: "Copy installation file into tmp"
  copy:
    src: "{{gradle_version}}-bin.zip"
    dest: "/tmp/{{gradle_version}}-bin.zip"
    mode: 0664
  when: gradle_from_source == false

- name: "Download gradle from source"
  get_url:
    url: 'https://services.gradle.org/distributions/{{gradle_version}}-bin.zip'
    dest: "/tmp/{{gradle_version}}-bin.zip"
    mode: 0664
  when: gradle_from_source

- name: "Create installation directory"
  file:
    path: "{{gradle_base_dir}}"
    state: directory
    recurse: yes

- name: "Unarchive gradle zip file"
  unarchive:
    src: "/tmp/{{gradle_version}}-bin.zip"
    dest: "{{ gradle_base_dir }}"
    owner: root
    group: root
    mode: 0775

- name: "Setup enviroment variable GRADLE_HOME"
  template:
    src: gradle.sh.j2
    dest: /etc/profile.d/gradle.sh
    owner: root
    group: root
    mode: 0775

- name: "GRADLE: Eliminate temporary files"
  file:
    path: "/tmp/{{gradle_version}}-bin.zip"
    state: absent
