---
- set_fact:
    jre_version: java-1.8.0-openjdk
    jdk_version: java-1.8.0-openjdk-devel

- name: "Install Java (JDK) {{jdk_version}}"
  yum:
    name: "{{jdk_version}}"
    state: present

- name: "Configure JAVA_HOME"
  become: yes
  lineinfile:
    dest: "/etc/profile.d/java.sh"
    line: "{{ item }}"
    state: present
    create: yes
    mode: 755
  with_items:
    - "export JAVA_HOME=/usr/lib/jvm/{{jdk_version | regex_replace('-devel', '') }}"
    - "export PATH=$PATH:$JAVA_HOME/bin"
